### ISSUE TITLE
StratisD process keeps running after quitting wallet

### ISSUE THREAD

**Issue by Danny-A** [stratisproject/FullNodeUI#20] opened 2017-12-20 07:48 UTC
After quitting the wallet on OSX High Sierra, the StratisD process keeps running in the background very heavily.

**Comment by dev0tion** [comment] 2017-12-20 14:13
Hi @Danny-A, thanks.
We are aware and working on it.

**Comment by bokobza** [comment] 2018-01-08 16:52
Duplicate of https://github.com/stratisproject/Breeze/issues/314
Will be fixed together.

**Closed by bokobza** 2018-01-08 16:52 UTC
