### ISSUE TITLE
Node daemon occasionally stays after Stratis Wallet is closed

### ISSUE THREAD

**Issue by noescape00** [stratisproject/FullNodeUI#26] opened 2018-01-30 10:48 UTC
![err](https://user-images.githubusercontent.com/10259355/35562312-0619de12-05c4-11e8-86f2-ab760131f677.png)

**Comment by bokobza** [comment] 2018-01-30 10:49
Duplicate of https://github.com/stratisproject/Breeze/issues/314
I'm actually working on this as we speak 😆

**Closed** 2018-01-30 10:50 UTC

**Comment by noescape00** [comment] 2018-01-30 10:52
Oh, didn't know. 
Awesome, @bokobza!
